on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: testing ${{ matrix.job.os }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Cargo test
        run: cargo test